Update gh-pages.yml

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -14,40 +14,16 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-      # - name: Checkout Repository
-      #   uses: actions/checkout@v2
-        
-      # - name: Get GitHub Pages status
-      #   run: |
-      #     REPO_OWNER="GovardhanKanala"
-      #     REPO_NAME="nova"
-      #     BRANCH="gh-pages"
-      #     GITHUB_TOKEN="${{ secrets.GITHUBTOKEN }}"
-          
-      #     API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/deployments?environment=github-pages&sha=${BRANCH}"
-          
-      #     # Save the response to a temporary file
-      #     curl -s -H "Authorization: token ${GITHUBTOKEN}" ${API_URL} > response.json
-          
-      # - name: Check GitHub Pages status
-      #   run: |
-      #     # Read the response from the temporary file
-      #     response=$(cat response.json)
-          
-      #     if [[ -z "$response" ]]; then
-      #       echo "No response from GitHub API. Proceeding with publishing."
-      #     else
-      #       in_progress=$(echo "$response" | jq -r '.[0].status // empty')
-      #       if [[ -z "$in_progress" ]]; then
-      #         echo "No ongoing deployment. Proceeding with publishing."
-      #       elif [[ "$in_progress" == "in_progress" ]]; then
-      #         echo "GitHub Pages deployment is in progress. Waiting for 1 minute before retrying."
-      #         sleep 60
-      #       else
-      #         echo "Unexpected status. Proceeding with publishing."
-      #       fi
-      #     fi
-
+      - name: Check if previous publishing is in progress
+        id: check_publishing
+        run: |
+          if [ -f .github/PUBLISH_IN_PROGRESS ]; then
+            echo "Another publishing operation is in progress. Retrying..."
+            exit 78 # Exit with a special code to trigger a retry
+          fi
+      - name: Set flag to indicate publishing in progress
+        if: ${{ steps.check_publishing.outcome != 'success' }} # Only set the flag if it's not in progress
+        run: touch .github/PUBLISH_IN_PROGRESS
       - name: Generate Sample File
         run: |
           echo "Hello, GitHub Pages! Generated at $(date)" > index.html
@@ -60,3 +36,6 @@ jobs:
           publish_branch: gh-pages
           allow_empty_commit: true
           commit_message: 'Publish sample file to GitHub Pages'
+
+      - name: Cleanup after publishing
+        run: rm -f .github/PUBLISH_IN_PROGRESS
